Comment...
 h1: Incorrect Revoke Fails to Revoke An Oracle
Comment...
 h2: GIVEN an oracle contract and a revoke message signed by another account.
Creating contract
 -> (Pair {Elt "XTZ-USD" (Pair "0" (Pair "0" (Pair 0 (Pair 0 (Pair 0 (Pair 0 0))))))} (Some "edpkumfjciYdSYPzFt5dzWt9k974Wnp2qPwHqqjfsJvEwJWpYJnFdW"))
 => ./.smartpy_out/Incorrect_Revoke_Fails_to_Revoke_An_Oracle_interpreted/testContractTypes.0.2.tz 2
 => ./.smartpy_out/Incorrect_Revoke_Fails_to_Revoke_An_Oracle_interpreted/testContractCode.0.2.tz 159
 => ./.smartpy_out/Incorrect_Revoke_Fails_to_Revoke_An_Oracle_interpreted/testContractCode.0.2.tz.json 317
 => ./.smartpy_out/Incorrect_Revoke_Fails_to_Revoke_An_Oracle_interpreted/testPrettyPrint.0.2.py 22
Comment...
 h2: WHEN revoke is called
Comment...
 h2: THEN the call fails
Executing revoke(sp.reduce(sp.make_signature(secret_key = sp.reduce(sp.test_account("Incorrect_Account").secret_key), message = sp.pack(sp.none), message_format = 'Raw')))...
 -> --- Expected failure in transaction --- WrongCondition in line 119: sp.check_signature(self.data.publicKey.open_some(), params, sp.pack(sp.set_type_expr(sp.none, sp.TOption(sp.TKey))))
Comment...
 h2: AND future updates succeed
Executing update(sp.set_type_expr({'XTZ-USD' : (sp.reduce(sp.make_signature(secret_key = sp.reduce(sp.test_account("Test1").secret_key), message = sp.pack(('XTZ-USD', (sp.timestamp(1), (sp.timestamp(2), (3, (4, (5, (6, 7)))))))), message_format = 'Raw')), (sp.timestamp(1), (sp.timestamp(2), (3, (4, (5, (6, 7)))))))}, sp.TMap(sp.TString, sp.TPair(sp.TSignature, sp.TPair(sp.TTimestamp, sp.TPair(sp.TTimestamp, sp.TPair(sp.TNat, sp.TPair(sp.TNat, sp.TPair(sp.TNat, sp.TPair(sp.TNat, sp.TNat))))))))))...
 -> (Pair {Elt "XTZ-USD" (Pair "1" (Pair "2" (Pair 3 (Pair 4 (Pair 5 (Pair 6 7))))))} (Some "edpkumfjciYdSYPzFt5dzWt9k974Wnp2qPwHqqjfsJvEwJWpYJnFdW"))